steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull asia.gcr.io/$PROJECT_ID/${_REPOSITORY_NAME}:$(cat tag.txt) || exit 0
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t asia.gcr.io/$PROJECT_ID/${_REPOSITORY_NAME} .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker push "asia.gcr.io/$PROJECT_ID/${_REPOSITORY_NAME}"
