steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull asia.gcr.io/$PROJECT_ID/google_jwt_verifier || exit 0
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t asia.gcr.io/$PROJECT_ID/google_jwt_verifier .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker push "asia.gcr.io/$PROJECT_ID/google_jwt_verifier"
